name: reactive_ble_windows
description: Unofficial Windows implementation for the flutter_reactive_ble plugin.
version: 5.2.0
homepage: https://github.com/PhilipsHue/flutter_reactive_ble
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_ble_platform_interface: ^5.3.1
  win_ble: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

flutter:
  plugin:
    implements: flutter_reactive_ble
    platforms:
      windows:
        dartPluginClass: ReactiveBleWindowsPlatform
